### ISSUE TITLE
Scorecard Problem on Wedding

### ISSUE THREAD

**Issue by davidkaufmann** [hamvocke/doppelkopf#26]
When playing a wedding the score isn't calculated correctly.
Obviously a wedding hasn't been implemented yet, nonetheless it will run the game as a "silent wedding"/"stille Hochzeit" ("silent solo"/"stiller Solo"). Summing all Points together should always equal zero, which isn't the case.

See images for details:

![Weddingbug](https://user-images.githubusercontent.com/12951672/101693921-9aa32d00-3a72-11eb-804a-94ff31291bc0.png)
![Weddingbug_again](https://user-images.githubusercontent.com/12951672/101693927-a0007780-3a72-11eb-8944-5c883ff3d107.png)

**Comment by hamvocke** [comment]
Good catch. This one's been bugging me for a while but I always postponed fixing it because, well, any kind of solo game doesn't work properly anyways. You're completely right, though. The game in fact plays a "stille Hochzeit" by default so we should make sure that the scoring works accordingly.

Calculating scores currently works on the implicit assumption that each party always has 2 players, that's why the implementations of `score.totalPoints()` and `score.points(partyName)` are pretty naive. I'll take a look at this over the next few days, might be a good opportunity to get a small but helpful refactoring in.

**Comment by hamvocke** [comment]
Fixed by #28
