### ISSUE TITLE
Affinities

### ISSUE THREAD

**Issue by hamvocke** [hamvocke/doppelkopf#32]
After announcements have landed, we have another way for players to reveal which party they belong to (until now they could only do so by playing a queen of clubs).

Whenever a player (human or computer) makes a move that's clearly showing that they belong to the Re or Kontra party (announcing or playing a queen of clubs) they reveal information that's relevant for other players and will change the way they collaborate with that player. We should track this kind of bilateral information between players as something I'd love to call "affinities". We can use affinities for a couple of things: 

* show a "re" or "kontra" party badge next to a player's name once it's 100% clear they belong to a given party
* tweak computer player's behavior to play high-ranked cards if it's clear that their partner is going to win the trick
* show a "fox caught" notification once it's clear to all players that this is a fox caught by the opposing party

An affinity value for another player could be a scale ranging from -1 (opponent) over 0 (unknown) to 1 (collaborator).

Keep in mind that affinities are always asynchronous information. One player might now that another player is their collaborator while the other player might be completely clueless.

An example:

* Player 1 announces "Re",  Player 2 and 3 are Kontra, Player 4 holds the other queen of clubs. With the announcement, the affinities for the players shift as follows:
   * Player 4 to Player 1: `1`
   * Player 3 to Player 1: `-1`
   * Player 2 to Player 1: `-1`
   * Player 4 remains completely unchanged (`0` for all)

To implement this, we need to react to certain **affinity events** in the game. Playing the queen of spades is one of them, announcing is another one. Later on, we can even expand this to include things that look likely but are not 100% clear signs of affinity - a player serving with a fox (or another high value card) early in he game. These events could shift the affinity score slightly (to be tweaked) in one direction.

The `game` instance could provide an `affinityEvent` method that will be triggered whenever an affinity event happens - a `trick` gets added a `queen of clubs` or a player makes an `announcement`. This method could go on and call every `player` in the current round to handle the given affinity event. There they could evaluate which player triggered the event, look at their own state ("am I Re? an I Kontra?") and update their affinities towards the player who triggered the event.

**Comment by davidkaufmann** [comment]
I was able to implement basic affinities with commit 110409e77614d5e789e87995b0d1d9f1324332f7.
So far we have following **affinityEvents** which are triggered and fully functional:

- announcements
- queen of clubs played

I believe these are the very basic events that aren't opinionated. Other events such as the high value cards or special moves like "abwerfen" should be opinionated are therefore should be implemented by the behavior class.

I haven't completely thought it through, but I believe this approach makes alot more sense. I might even think about including the affinities into the behaviour class, since these are very tighly coupled on a logical level.

Anyway, this will introduce new major possibilities in the AI.

I will try to create a pull request within this week. Although affinites aren't implemented in the behaviour yet (might do), I did spot some bugs in the AI and managed to fix them.

**Comment by hamvocke** [comment]
The approach sounds reasonable to me. And I agree, there are more opinionated events that can affect the affinity - but this should be something that behaviors take care of. Some players count cards really well, some don't. Some players play by a system and know that "playing a ten of diamonds in the second trick" means something specific (I'm just making stuff up here, I know there are certain maneuvers of this kind but I don't really know the exact rules). Certain behaviors could decide to let those things have an effect on the affinity while others don't.

I'll try to take a closer look at your PR this weekend. Thanks for getting this in!
