### ISSUE TITLE
UI Improvements

### ISSUE THREAD

**Issue by davidkaufmann** [hamvocke/doppelkopf#34]
Playing the Game for the first time on mobile I believe I saw a few UI Flaws.
![default ui](https://user-images.githubusercontent.com/12951672/102701548-4ceba900-4258-11eb-9dd4-ea9560cf338d.png)
Image you play the game on a relatively small device, we have the issue that flexbox wraps into the next line, creating 3 cards in the first row and one in the second. Technically we still know that the order doesn't change, seeing the last card wrapping into the second line is really inconvenient, especially when cards just keep 'plopping' in. I strongly believe having static card slots where players drop their cards will simulate a real table and will improve intuition and therefore usability.

Another issue with this screenshot becomes clear when asking yourself the question. Who started the round? You need to calculate back. I suggest highlighting the player who actually started the trick will be another quick and dirty benefit to the game.

Take a look at the attached screenshot (which was modified using paint) to get a feeling what i mean.
Indeed, another great and easy improvement would be to highlight the winner of the trick with another colour.

![suggested improvements](https://user-images.githubusercontent.com/12951672/102701554-5b39c500-4258-11eb-9bc2-1ef0da22c20d.png)

Colourwise I like yellow since it's different to the blue and red colour scheme and blends into the current scheme very well (obviously not this yellow).
Technically i would suggest using gridview and the order property for the card-layout.

**Comment by hamvocke** [comment]
These are valid points, and thanks for thinking about ways to improve the situation!

Having the flexbox wrap if there's not enough space was a deliberate decision, before that the page would start scrolling horizontally if the device viewport was not wide enough. I totally see how this is not optimal, though.

Not sure if you noticed (I never knew if this feature was hidden too much): if you hover (or tap) a card in the current trick, there'll be a small popover showing who played this card.

Revamping the current trick UX has been on the back of my mind for a bit now, it's just that working with small viewports can be super tedious which is why I've been putting it off for a while. I like the proposed design with cards being in north/east/south/west locations. With `display: grid` this should doable in a stable way for different viewport sizes. A while ago I thought about showing the current trick a little more life-like, with the cards being rotated so that they look like the players actually played it from their position at the table. Then, we could even add a slight amount of randomness so cards show up _a little_ different each time. And finally, they could overlap a bit so you could clearly see which card came first (it's the one with the lowest `z-index`). Rotation, randomness and overlapping are all optional bits and maybe even way too much for the rather clear and linear aesthetic of the game. I think starting with your proposed `grid` alignment opens room for a lot of experimentation in those regards and will be a step forward.

And then there's the point of "who wins the trick?". This whole `Der Stich geht an XYZ` has been there since the early days and feels rather clumsy to me today. It's a good thing for beginners who don't fully understand the game yet but for more experienced players it seems pretty blunt. Maybe highlighting the name of the winning player is indeed the way to go. Alternatively, we could show a small `badge` icon (see [here](https://feathericons.com/), this is the icon set we're using) next to their name.

I'll add two new issues to the roadmap, one for the card alignment, one for tracking the winner of the current trick. Feel free to start tackling them if you're up for it!

**Comment by davidkaufmann** [comment]
Hi Ham,

i would love to work on a basic implementation of what we put together in this conversation. Taking small steps is just the right way - we can add complexity as we go on 😄
I agree with the badge, and will implement the flag icon for the starting player, although i believe it would be a good idea to have the flag for the player who's currently on turn (will come in handy when we tackle network play).

P.S: I know about the tooltip option and i agree it's too hidden, since i only found out about it quite recently.

**Comment by hamvocke** [comment]
Awesome! I agree, let's get something small and easy in first, we can always build on top of that later :)

**Comment by hamvocke** [comment]
Tracked in two separate bugs. Since both are done, I'm closing this one, too.
