### ISSUE TITLE
Playing the card directly, if it is the player's turn

### ISSUE THREAD

**Issue by davidh38** [hamvocke/doppelkopf#43]
If it is the turn of the player, it would be comfortable to directly play the card, instead of pressing on **next trick**.

**Comment by davidkaufmann** [comment]
Hi there,

thx for giving feedback 👍🏻
I personally believe that the next trick functionality is implemented because the game is lacking a "show last trick" option. This way it is possible to memorize the cards. I will probably add this to the roadmap at some point, since it adds great value to the game and could be implemented quite easily - maybe even for somebody who wants to start contributing to the project 😉

It's definately more convenient to leave out the button press (on your own turn), but ingame it obviously acts as an event to start the next trick. Right now I only see some problems coming towards us implementing this feature request.

I can see this being implemented though, since - as fas as I know - ham is currently working on getting the multiplayer part to work. Having each player "accept" the next trick wouldn't be very convenient and worsens the game "fluentlessness", whereas showing a modal if a player needs to have a look at the last trick works quite well.

Anyway thanks for your input and lets see what ham says :)

**Comment by hamvocke** [comment]
Pressing the _next trick_ button is more or less the digital equivalent of grabbing a trick from the table before playing the next card. I agree that it's a bit clumsy.

What would a smoother user experience look like? I could imagine replacing the _next trick_ button with a timer-based delay. Instead of showing the _next trick_ button we wait a bit (2-5 seconds maybe, gotta play around with those values), move the current trick to the winner's trick stack and then let either the computer player autoplay their next move or let the current player play the next card.

**Comment by davidh38** [comment]
Hey guys,
i did not express myself very precise.

@davidkaufmann @hamvocke
**show last trick option + timer-based delay with animation during the last card** would be best for all cases, I agree. 
For now my suggestion is: 
It is the player's turn to act and **the last trick was the player's trick**, then he could instead of pressing the "next trick" button, directly play the card.

**Comment by davidkaufmann** [comment]
@davidh38 long time no see 😄
I implemented this, you can take a look at the PR, works like a charm 👍🏻

**Comment by hamvocke** [comment]
Thanks for the fix @davidkaufmann. It's an interesting approach though I'm not sure if I personally like it. Sometimes I have to press the _next trick_ button and in other cases I can play the card directly. **But**: If I don't like it, I can just keep pressing the _next trick_ button every time, so this is overall an improvement even if it's not my personal preference :slightly_smiling_face: 

Thanks to both of you for raising this idea and getting it shipped.
