### ISSUE TITLE
UI Feature: Last trick played

### ISSUE THREAD

**Issue by davidkaufmann** [hamvocke/doppelkopf#44]
As mentioned in issue #43, it would be a decent addition to have an additional button within the UI to see the last trick.

I can imagine one of these icons in the top right corner, next to the settings icon: ActivityIcon, InfoIcon or RotateCcwIcon from the [icon pack we're currently using](https://vue-feather-icons.egoist.sh/).

Pressing the icon could display a modal, using parts of the vue trick component, displaying the trick with the appropriate grid, maybe even showing the names.
Currently we're going a "functionality before design" approach, so don't spend too much time on optics - we can polish and make everything shiny later 😃👍🏻

**Comment by hamvocke** [comment]
Could've sworn that there was a card for this somewhere already. Looks like I was wrong.

As an alternative to showing an extra button, we could think about clicking the trick stack (and maybe showing a popover to indicate that there's something there) to see the last trick. An icon in the top-right corner would work, too but its kind of an awkward place for mobile users since it's pretty far away from their thumbs. On the other hand, showing the last trick is not an action that's used as frequently as moving on to the next trick, so this might be okay.
