### ISSUE TITLE
Feature Ideas

### ISSUE THREAD

**Issue by lkoehl** [hamvocke/doppelkopf#7]
Think about the game some things come to my mind where this could be going and how it can be improved. 

First something about the visuals:
- the notification bar is spamable to so other content is seeable. Limiting it to 1 seems reasonable because right now i cant think for a moment to display to notifications at the same time or within the 4 seconds its shown. 
- Since there is a RingQueue it would be nice to have a visual indicator who’s turn it is. 
- It annoys me a little, that the cards of the player are not centered, because the trick stack is included for the centering. Centering the cards and therefore push everything now as it is just a little to the right, when looking at the human player. 
- The scorecard. I would think it is a great idea to display the last played round at the top to make it easily seeable. This would mean a flip of the table. 
- Longer Names are truncated. There should be a nice way to show names fully, no matter the screen size. Font scaling or a little different design could be possible
- Aligning the text to the left at the results and on the right in the points table isn’t doing it for me. Maybe always aligning the text to the right might be an idea

Functionality
 - Adding settings to the game. And moving the language option into there. 
- Table Settings to allow for different game rules to be turned on or off, like „Schweinchen“, „Zweite Dulle sticht die Erste“ or „Charly am End“
-Thinking way further it would be nice to play online against friends

**Comment by davidkaufmann** [comment]
A few (unfiltered) suggestions I got from family when showing them the game (all of them were playing mobile...)

- It's not visible who starts.
- Notifications aren't obvious - they're hardly to see at all. Better add a speech bubble to the corresponding player.
- Trick should be taken with a timer, it's always possible to see the previous trick. Games are faster this way.
- Mouse click on the finished trick to take the trick would make the game even faster, additionally it's more convenient than the button.
- Some kind of reminder if you're starting and not taking your turn.

IMHO it boils down to these things being real improvements
- Speech bubbles as UI improvements - mainly because of form and colour contrast
- Fast game iteration: starting next trick either with click on the trick or through timer
